Renovate Combined Pull Request (#915)
* Update plugin org.sonarqube to v6.0.1.5171

* Update dependency hashicorp/terraform to v1.10.0

* Update dependency com.fasterxml.jackson:jackson-bom to v2.18.2

* Update dependency com.fasterxml.jackson.core:jackson-databind to v2.18.2

* Update dependency org.pitest:pitest to v1.17.2

* Update dependency pmd to v7.8.0

* pitest version reverted 1.17.2 -> 1.17.0 due to NoSuchMethodError

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: github-actions <github-actions@github.com>
Co-authored-by: Mike Brown <michael.brown@hmcts.net>
Co-authored-by: mikebrownccd <104495891+mikebrownccd@users.noreply.github.com>